server:
  port: 8008
spring:
  application:
    name: evalute8008
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.211.55.7:3306/happyDb1
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 10.211.55.7
    port: 6379
    database: 0
    password: 123456
    sentinel:
      master: mymaster
      nodes: 10.211.55.7:26379,10.211.55.7:26380,10.211.55.7:26381
mybatis:
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: evalute8008
    prefer-ip-address: true
info:
  author: zzei
  server:
    name: evalute8008
logging:
  level:
    com.zei.happy.mapper: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql