server:
  port: 8010
spring:
  application:
    name: sso8010
  redis:
    host: 10.211.55.7
    port: 6379
    database: 0
    password: 123456
    sentinel:
      master: mymaster
      nodes: 10.211.55.7:26379,10.211.55.7:26380,10.211.55.7:26381
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: sso8010
    prefer-ip-address: true
info:
  author: zzei
  server:
    name: sso8010
ribbon:
  eureka:
    enabled: true