server:
  port: 9001
spring:
  application:
    name: zuul9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: zuul9001
    prefer-ip-address: true
info:
  author: zzei
  server:
    name: zuul9001
#zuul:
#  prefix: /                     #统一前缀
#  ignored-services: "*"
#  routes:
#    provider:                    #路由微服务
#      serviceId: provide8002    #微服务application.name 若该服务有多个，则自动采用轮询负载均衡
#      path: /provider/**         #路由路径
#    consumer:
#      serviceId: consumer8003
#      path: /consumer/**